name: currytabetaiappnihonbashi
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  image_picker: ^1.0.4
  logger: any
  dio: ^5.1.2
  retrofit: ^4.0.1
  freezed_annotation:
  json_annotation: 
  json_serializable: 
  provider:
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  permission_handler: ^11.1.0
  riverpod_annotation: ^2.3.3
  share: ^2.0.4
  share_plus: ^7.2.1

 
 
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

  lottie: ^1.2.1
  firebase_core: ^1.0.1
  firebase_auth: ^1.0.1
  google_sign_in: ^5.0.0
  retrofit_generator:
  build_runner:
  freezed:
  
dependency_overrides:
  firebase_auth_platform_interface: 6.7.0
  firebase_core_platform_interface: 4.5.1
 
flutter:
  uses-material-design: true
  assets:
    - assets/images/india19-37359.jpg
    - assets/images/searchbackground.png
    - assets/images/kumaluacon.png
    - assets/images/hotelcurry.png
    - assets/images/indeiacurry.png
    - assets/images/japancurry.png
    - assets/images/minamicurry.png
    - assets/images/soupcurry.png
    - assets/images/spicecurry.png
    - assets/images/srilankacurry.png
    - assets/images/taicurry.png
    - assets/images/sample.png
    - assets/images/android_neutral_rd_na@1x.png
    - assets/images/1702.png


