name: currytabetaiappnihonbashi
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
 

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/india19-37359.jpg
    - assets/images/searchbackground.png
    - assets/images/kumaluacon.png
    - assets/images/hotelcurry.png
    - assets/images/indeiacurry.png
    - assets/images/japancurry.png
    - assets/images/minamicurry.png
    - assets/images/soupcurry.png
    - assets/images/spicecurry.png
    - assets/images/srilankacurry.png
    - assets/images/taicurry.png
    - assets/images/sample.png




