name: currytabetaiappnihonbashi
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  image_picker: ^1.0.7
  logger: any
  dio: ^5.4.1
  retrofit: ^4.1.0
  freezed_annotation:
  json_annotation: ^4.8.1
  json_serializable: 
  provider:
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  permission_handler: ^11.1.0
  riverpod_annotation: ^2.3.3
  share: ^2.0.4
  share_plus: ^7.2.1
  keyboard_actions: ^4.2.0
  firebase_auth: ^4.17.2
  firebase_core: ^2.25.2
  cloud_firestore: ^4.15.5
  analyzer: ^6.2.0
  firebase_database: ^10.4.6
  firebase_storage: ^11.6.7
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^5.0.0
  cloud_functions: ^4.6.8
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

  lottie: ^1.2.1
  retrofit_generator:
  build_runner:
  freezed:
  

 
flutter:
  uses-material-design: true
  assets:
    - assets/images/india19-37359.jpg
    - assets/images/searchbackground.png
    - assets/images/kumaluacon.png
    - assets/images/hotelcurry.png
    - assets/images/indeiacurry.png
    - assets/images/japancurry.png
    - assets/images/minamicurry.png
    - assets/images/soupcurry.png
    - assets/images/spicecurry.png
    - assets/images/srilankacurry.png
    - assets/images/taicurry.png
    - assets/images/sample.png
    - assets/images/android_neutral_rd_na@1x.png
    - assets/images/1702.png
    - assets/images/homekari.png
    - assets/images/homekari2.png


